### ISSUE TITLE
Help with BuildModel, 4 accumulator LBA

### ISSUE THREAD

**Issue by davidt0x** [yxlin/ggdmc#3]
Hi,

Sorry if this question is a bit basic but I was wondering if you could help me understand the BuildModel command. I am trying to setup an LBA model for an experiment I have involving a 4-choice task. I also have 4 stimuli that have a shape and color (blue_diamond, blue_heart, green_diamond, and green_heart). In addition, I have a task indicator which is given to the subject that specifies whether to attend to the shape or color of the stimuli. The subject is then asked to specify the correct response (blue, green, heart, diamond).

Do you think you could provide me with some insight into how to express such a model to ggdmc via the BuildModel command. Is it possible? I tried to follow along with this 3 accumulator example but I got a bit lost (https://yxlin.github.io/cognitive-model/lba3/). Also, incidentally there seems to be an error in the script in the predict_one function with mismatched brackets.

Thanks for the package and any help you can give me.

**Comment by yxlin** [comment]
Hi davidt0x,

Thank you for raising the question and informing me the errors in the lba3 example. I have updated the example and hope I did not introduce any new bugs or errors. I ran a few tests (on a remote server) of the 4-accumulator example in the updated lba3 tutorial.  Just be aware that it would take a lot of time when fitting hierarchical version of that model.

Sincerely,

Yi-Shin

**Comment by davidt0x** [comment]
Thanks so much for your help, I will take a look this week.

Dave

**Comment by davidt0x** [comment]
Hi Yi-Shin,

The link that you posted (https://yxlin.github.io/cognitive-model/lba3/) seems to be broken now. It was working before but not anymore. Just a heads up.

Dave

**Comment by yxlin** [comment]
HI Dave,

Thanks so much. It should show up now. I mis-typed a "y" in the control code, so it does not appear.

Yi-Shin
